spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_smart_schedule?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false